[project]
name = "lkapi"
version = "0.1.0"
description = "Example client code to work with the Lightkeeper API"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.3",
    "pandas>=2.2.3",
    "requests>=2.32.3",
]
